"""
Tirumala future-safe inference layer for the 77-feature Optuna CatBoost model.

Primary model:
    tirumala_future_safe_optuna.cbm

This module is intentionally tied to the actual saved model at runtime:
- feature names/order come from model.feature_names_
- categorical positions come from model.get_cat_feature_indices()
- date/calendar/panchang/vacation/season features come from lib.features
- future-known TTD event features come from the 2026-2027 event CSV
- historical crowd-context features are constructed only from dates before
  the target date; recursive forecasts are used only after the last actual
  date when forecasting multiple future dates
- same-day operational bulletin fields are never used

Public API expected by the current Streamlit app:
    predict_pilgrims(target_date, events_df=None)
    forecast_until(end_date_iso, events_df=None)
"""
from __future__ import annotations

import functools
import re
from datetime import date, timedelta
from pathlib import Path

import numpy as np
import pandas as pd
from catboost import CatBoostRegressor, Pool

from . import features as feat


LIB_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = LIB_DIR.parent

MODEL_PATH = PROJECT_ROOT / "tirumala_future_safe_optuna.cbm"
MERGED_PATH = PROJECT_ROOT / "data" / "merged.csv"
EVENTS_PATH = PROJECT_ROOT / "data" / "ttd_tirumala_events_2026_2027.csv"

BAND_SIZE = 5000

# These should NOT appear in the future-safe Optuna model.
FORBIDDEN_OPERATIONAL_COLUMNS = {
    "tonsures_raw",
    "hundi_raw",
    "laddu_raw",
    "annaprasadam_raw",
    "medical_raw",
    "waiting_compartments_raw",
    "waiting_time_raw",
}


# ---------------------------------------------------------------------------
# Model loading / schema
# ---------------------------------------------------------------------------

@functools.lru_cache(maxsize=1)
def load_model() -> CatBoostRegressor:
    if not MODEL_PATH.exists():
        raise FileNotFoundError(
            f"Future-safe Optuna model not found: {MODEL_PATH}\n"
            "Copy tirumala_future_safe_optuna.cbm into the project root."
        )
    model = CatBoostRegressor()
    model.load_model(str(MODEL_PATH))
    return model


@functools.lru_cache(maxsize=1)
def model_schema() -> tuple[list[str], list[int]]:
    model = load_model()
    names = list(model.feature_names_)
    cat_idx = sorted(model.get_cat_feature_indices())

    forbidden = [c for c in names if c in FORBIDDEN_OPERATIONAL_COLUMNS]
    if forbidden:
        raise RuntimeError(
            "The selected model contains same-day operational features, "
            f"so it is NOT the expected future-safe model: {forbidden}"
        )

    # These are the known non-history features generated by features.py.
    feature_columns = set(getattr(feat, "FEATURE_COLUMNS", [])) - {"date"}
    event_columns = {
        "ttd_event_count",
        "is_ttd_event",
        "is_major_ttd_event",
        "ttd_event_importance",
        "ttd_event_names",
        "ttd_event_types",
        "major_ttd_events",
        "is_brahmotsavam_event",
        "is_garuda_seva_event",
        "is_pavitrotsavam",
        "is_rathasaptami",
    }
    history_columns = {
        "pilgrims_lag_1d",
        "pilgrims_lag_7d",
        "pilgrims_lag_14d",
        "pilgrims_same_dow_lag_1w",
        "pilgrims_roll7_mean",
        "pilgrims_roll28_mean",
        "pilgrims_prev_year",
        "pilgrims_prev_2year",
        "pilgrims_prev_3year",
        "pilgrims_prev_364d",
        "prior_years_same_dow_mean",
        "prior_years_same_month_dow_mean",
    }

    unexplained = [
        c for c in names
        if c not in feature_columns
        and c not in event_columns
        and c not in history_columns
    ]
    if unexplained:
        raise RuntimeError(
            "Model expects unsupported feature(s): "
            f"{unexplained}"
        )

    return names, cat_idx


# Backward-compatible internal name used by tests / earlier shell checks.
_model_schema = model_schema


# ---------------------------------------------------------------------------
# Historical data
# ---------------------------------------------------------------------------

@functools.lru_cache(maxsize=1)
def load_merged() -> pd.DataFrame:
    if not MERGED_PATH.exists():
        raise FileNotFoundError(f"Historical data not found: {MERGED_PATH}")

    df = pd.read_csv(MERGED_PATH, dtype=str)
    required = {"date", "pilgrims_raw"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"merged.csv missing required columns: {sorted(missing)}")

    df["date"] = pd.to_datetime(df["date"], errors="coerce").dt.normalize()
    df["pilgrims"] = pd.to_numeric(
        df["pilgrims_raw"].astype(str).str.replace(",", "", regex=False),
        errors="coerce",
    )

    return (
        df.dropna(subset=["date"])
        .drop_duplicates("date", keep="last")
        .sort_values("date")
        .reset_index(drop=True)
    )


@functools.lru_cache(maxsize=1)
def actual_series() -> pd.Series:
    df = load_merged()
    return (
        df.dropna(subset=["pilgrims"])
        .set_index("date")["pilgrims"]
        .astype(float)
        .sort_index()
    )


_known_actuals = actual_series


def _last_actual_date() -> date | None:
    actuals = actual_series()
    return actuals.index.max().date() if not actuals.empty else None


# ---------------------------------------------------------------------------
# Event data + event feature family
# ---------------------------------------------------------------------------

@functools.lru_cache(maxsize=1)
def load_events() -> pd.DataFrame:
    if not EVENTS_PATH.exists():
        return pd.DataFrame(
            columns=[
                "start_date", "end_date", "event_name", "shrine", "event_type",
                "major_event", "importance", "calendar_label", "source", "scope",
            ]
        )

    events = pd.read_csv(EVENTS_PATH, dtype=str)
    for col in ("start_date", "end_date"):
        events[col] = pd.to_datetime(events[col], errors="coerce").dt.normalize()

    for col in ("event_name", "event_type", "calendar_label"):
        if col not in events.columns:
            events[col] = ""
        events[col] = events[col].fillna("").astype(str)

    if "major_event" not in events.columns:
        events["major_event"] = 0
    events["major_event"] = pd.to_numeric(events["major_event"], errors="coerce").fillna(0).astype(int)

    if "importance" not in events.columns:
        events["importance"] = 0.0
    events["importance"] = pd.to_numeric(events["importance"], errors="coerce").fillna(0.0)

    return events.dropna(subset=["start_date", "end_date"]).copy()


def _event_features_for_date(day: pd.Timestamp) -> dict:
    events = load_events()
    day = pd.Timestamp(day).normalize()

    if events.empty:
        active = events
    else:
        active = events.loc[
            (events["start_date"] <= day)
            & (events["end_date"] >= day)
        ]

    if active.empty:
        return {
            "ttd_event_count": 0,
            "is_ttd_event": 0,
            "is_major_ttd_event": 0,
            "ttd_event_importance": 0.0,
            "ttd_event_names": "",
            "ttd_event_types": "",
            "major_ttd_events": "",
            "is_brahmotsavam_event": 0,
            "is_garuda_seva_event": 0,
            "is_pavitrotsavam": 0,
            "is_rathasaptami": 0,
        }

    names = active["event_name"].astype(str).tolist()
    types = active["event_type"].drop_duplicates().astype(str).tolist()
    major_mask = active["major_event"].eq(1)
    major_names = active.loc[major_mask, "event_name"].astype(str).tolist()

    text = " ".join(
        active["event_type"].astype(str).tolist()
        + active["event_name"].astype(str).tolist()
    ).lower()

    def has_any(*terms: str) -> int:
        return int(any(term.lower() in text for term in terms))

    return {
        "ttd_event_count": int(len(active)),
        "is_ttd_event": 1,
        "is_major_ttd_event": int(major_mask.any()),
        "ttd_event_importance": float(active["importance"].max()),
        "ttd_event_names": " | ".join(names),
        "ttd_event_types": " | ".join(types),
        "major_ttd_events": " | ".join(major_names),
        "is_brahmotsavam_event": has_any("brahmotsavam"),
        "is_garuda_seva_event": has_any("garuda seva", "garuda"),
        "is_pavitrotsavam": has_any("pavitrotsavam", "pavithrotsavam", "pavitrotsav"),
        "is_rathasaptami": has_any("rathasaptami", "rathasapthami", "ratha sapthami"),
    }


# ---------------------------------------------------------------------------
# Date-known features: reuse the uploaded lib/features.py unchanged
# ---------------------------------------------------------------------------

@functools.lru_cache(maxsize=4096)
def _date_features(day: date) -> dict:
    day = pd.Timestamp(day).normalize()
    frame = pd.DataFrame({"date": [day.strftime("%Y-%m-%d")]})

    frame = feat.add_calendar_features(frame)
    frame = feat.add_holiday_features(frame)
    frame = feat.add_panchang_features(frame)
    frame = feat.add_administrative_festival_features(frame)
    frame = feat.add_vacation_features(frame)
    frame = feat.add_season_features(frame)

    return frame.iloc[0].to_dict()


def _value_on(series: pd.Series, day: pd.Timestamp) -> float:
    value = series.get(pd.Timestamp(day).normalize(), np.nan)
    return np.nan if value is None or pd.isna(value) else float(value)


def _previous_year_value(day: pd.Timestamp, years: int, actuals: pd.Series) -> float:
    return _value_on(actuals, day - pd.DateOffset(years=years))


def _rolling_mean_before(day: pd.Timestamp, periods: int, history: pd.Series) -> float:
    dates = pd.date_range(
        end=day - pd.Timedelta(days=1),
        periods=periods,
        freq="D",
    )
    values = history.reindex(dates).dropna()
    return float(values.mean()) if not values.empty else np.nan


def _prior_same_weekday_average(day: pd.Timestamp, actuals: pd.Series) -> float:
    values = []
    for years_back in (1, 2, 3):
        base = day - pd.DateOffset(years=years_back)
        window = pd.date_range(
            start=base - pd.Timedelta(days=7),
            end=base + pd.Timedelta(days=7),
            freq="D",
        )
        for x in window:
            if x.weekday() != day.weekday():
                continue
            v = _value_on(actuals, x)
            if not pd.isna(v):
                values.append(v)
    return float(np.mean(values)) if values else np.nan


def _prior_same_month_weekday_average(day: pd.Timestamp, actuals: pd.Series) -> float:
    values = []
    for years_back in (1, 2, 3):
        base = day - pd.DateOffset(years=years_back)
        try:
            month_start = pd.Timestamp(year=base.year, month=day.month, day=1)
            month_end = month_start + pd.offsets.MonthEnd(1)
        except ValueError:
            continue
        for x in pd.date_range(month_start, month_end, freq="D"):
            if x.weekday() != day.weekday():
                continue
            v = _value_on(actuals, x)
            if not pd.isna(v):
                values.append(v)
    return float(np.mean(values)) if values else np.nan


def _history_features(day: pd.Timestamp, running: pd.Series, actuals: pd.Series) -> dict:
    day = pd.Timestamp(day).normalize()
    return {
        "pilgrims_lag_1d": _value_on(running, day - pd.Timedelta(days=1)),
        "pilgrims_lag_7d": _value_on(running, day - pd.Timedelta(days=7)),
        "pilgrims_lag_14d": _value_on(running, day - pd.Timedelta(days=14)),
        "pilgrims_same_dow_lag_1w": _value_on(running, day - pd.Timedelta(days=7)),
        "pilgrims_roll7_mean": _rolling_mean_before(day, 7, running),
        "pilgrims_roll28_mean": _rolling_mean_before(day, 28, running),
        "pilgrims_prev_year": _previous_year_value(day, 1, actuals),
        "pilgrims_prev_2year": _previous_year_value(day, 2, actuals),
        "pilgrims_prev_3year": _previous_year_value(day, 3, actuals),
        "pilgrims_prev_364d": _value_on(actuals, day - pd.Timedelta(days=364)),
        "prior_years_same_dow_mean": _prior_same_weekday_average(day, actuals),
        "prior_years_same_month_dow_mean": _prior_same_month_weekday_average(day, actuals),
    }


# ---------------------------------------------------------------------------
# Full 77-feature row + model inference
# ---------------------------------------------------------------------------

def build_feature_row(day: date, running_history: pd.Series, actuals: pd.Series) -> dict:
    day_ts = pd.Timestamp(day).normalize()
    row = _date_features(day_ts.date())
    row.update(_event_features_for_date(day_ts))
    row.update(_history_features(day_ts, running_history, actuals))

    names, _ = model_schema()
    missing = [name for name in names if name not in row]
    if missing:
        raise RuntimeError(
            "Feature construction is missing model columns: "
            f"{missing}"
        )
    return row


def _predict_row(row: dict) -> float:
    model = load_model()
    names, cat_idx = model_schema()
    cat_positions = set(cat_idx)

    X = pd.DataFrame(
        [{name: row.get(name, np.nan) for name in names}],
        columns=names,
    )

    for i, name in enumerate(names):
        if i in cat_positions:
            X[name] = X[name].map(
                lambda v: "" if v is None or pd.isna(v) else str(v)
            )
        else:
            X[name] = pd.to_numeric(X[name], errors="coerce")

    prediction = float(model.predict(Pool(X, cat_features=cat_idx))[0])
    return max(0.0, prediction)


# ---------------------------------------------------------------------------
# Wait-time display estimate (dashboard only; not a model input)
# ---------------------------------------------------------------------------

def _parse_wait(raw) -> tuple[float, float] | None:
    if raw is None or (isinstance(raw, float) and pd.isna(raw)):
        return None
    nums = [
        float(x)
        for x in re.findall(
            r"\d+(?:\.\d+)?",
            str(raw).replace("\u2013", "-"),
        )
    ]
    if not nums:
        return None
    if len(nums) == 1:
        return nums[0], nums[0]
    return min(nums[0], nums[1]), max(nums[0], nums[1])


@functools.lru_cache(maxsize=1)
def _wait_bins() -> pd.DataFrame:
    df = load_merged()
    if "waiting_time_raw" not in df.columns:
        return pd.DataFrame(columns=["band", "wait_lo", "wait_hi"])

    work = df.dropna(subset=["pilgrims", "waiting_time_raw"]).copy()
    parsed = work["waiting_time_raw"].apply(_parse_wait)
    keep = parsed.notna()
    work = work.loc[keep].copy()
    parsed = parsed.loc[keep]
    if work.empty:
        return pd.DataFrame(columns=["band", "wait_lo", "wait_hi"])

    work["wait_lo"] = parsed.map(lambda p: p[0])
    work["wait_hi"] = parsed.map(lambda p: p[1])
    work["band"] = (work["pilgrims"] // BAND_SIZE) * BAND_SIZE

    return (
        work.groupby("band")[["wait_lo", "wait_hi"]]
        .median()
        .reset_index()
        .sort_values("band")
    )


def _estimate_wait(point: float) -> tuple[float, float] | None:
    bins = _wait_bins()
    if bins.empty:
        return None
    band = (point // BAND_SIZE) * BAND_SIZE
    idx = (bins["band"] - band).abs().idxmin()
    r = bins.loc[idx]
    return float(r["wait_lo"]), float(r["wait_hi"])


def _band(point: float) -> tuple[int, int]:
    lo = int(point // BAND_SIZE) * BAND_SIZE
    return lo, lo + BAND_SIZE


# ---------------------------------------------------------------------------
# Recursive future forecasting
# ---------------------------------------------------------------------------

@functools.lru_cache(maxsize=64)
def _forecast_through(end_d: date) -> tuple[tuple[pd.Timestamp, dict], ...]:
    actuals = actual_series()
    if actuals.empty:
        raise RuntimeError("No actual pilgrim history found in merged.csv.")

    last_actual = pd.Timestamp(actuals.index.max()).normalize()
    end_ts = pd.Timestamp(end_d).normalize()

    if end_ts <= last_actual:
        return tuple()

    # Actual historical values are immutable. Predictions are appended to a
    # separate running series only for dates beyond the actual-data horizon.
    running = actuals.copy().astype(float)
    results: dict[pd.Timestamp, dict] = {}

    cursor = last_actual + pd.Timedelta(days=1)
    while cursor <= end_ts:
        d = cursor.date()
        row = build_feature_row(d, running, actuals)
        point = _predict_row(row)
        running.loc[cursor] = point

        lo, hi = _band(point)
        results[cursor] = {
            "point_estimate": point,
            "range_low": lo,
            "range_high": hi,
            "wait_range_hours": _estimate_wait(point),
            "feature_row": row,
        }
        cursor += pd.Timedelta(days=1)

    return tuple(results.items())


# ---------------------------------------------------------------------------
# Public API for app.py
# ---------------------------------------------------------------------------

def predict_pilgrims(target_date: date, events_df=None) -> dict:
    """Return actual historical value when available, otherwise forecast."""
    d = pd.Timestamp(target_date).normalize()
    actuals = actual_series()

    if d in actuals.index:
        point = float(actuals.loc[d])
        lo, hi = _band(point)
        return {
            "point_estimate": point,
            "range_low": lo,
            "range_high": hi,
            "wait_range_hours": _estimate_wait(point),
            "feature_row": {},
            "is_actual": True,
        }

    table = dict(_forecast_through(d.date()))
    if d not in table:
        raise ValueError(f"Unable to generate forecast for {d.date()}.")

    result = dict(table[d])
    result["is_actual"] = False
    return result


def forecast_until(end_date_iso: str, events_df=None) -> pd.DataFrame:
    end_d = date.fromisoformat(str(end_date_iso)[:10])
    table = dict(_forecast_through(end_d))

    records = [
        {
            "date": ts.date().isoformat(),
            "prediction": float(result["point_estimate"]),
            "lo": int(result["range_low"]),
            "hi": int(result["range_high"]),
            "wait": result.get("wait_range_hours"),
        }
        for ts, result in table.items()
    ]

    return pd.DataFrame(
        records,
        columns=["date", "prediction", "lo", "hi", "wait"],
    ).sort_values("date").reset_index(drop=True)


# Compatibility aliases for debugging/tests.
_load_model = load_model